<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>
    
    <ItemGroup>
        <SupportedPlatform Include="browser" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.7" />
        <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.12" />
        <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.12" />
        <PackageReference Include="MudBlazor" Version="9.9.0" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="wwwroot\" />
    </ItemGroup>

</Project>
