## Structirizr inde i 'C4 diagram*' anvender port 8081
services:

# ──────────────────────────────────────────────────────────────────────────────
#        Articles
# ──────────────────────────────────────────────────────────────────────────────

  ## Articles from Europe
  articledb-eu:
    image: postgres:18-trixie
    environment:
      POSTGRES_DB: articles
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Postgres1234
    volumes:
      - ./database/init/article/article_baseline.sql:/docker-entrypoint-initdb.d/01_article_baseline.sql:ro
      - ./database/queries/article/seed_reference_data.sql:/docker-entrypoint-initdb.d/02_seed_reference_data.sql:ro

  ## Articles from North America
  articledb-na:
    image: postgres:18-trixie
    environment:
      POSTGRES_DB: articles
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Postgres1234
    volumes:
      - ./database/init/article/article_baseline.sql:/docker-entrypoint-initdb.d/01_article_baseline.sql:ro
      - ./database/queries/article/seed_reference_data.sql:/docker-entrypoint-initdb.d/02_seed_reference_data.sql:ro

  ## Articles from South America
  articledb-sa:
    image: postgres:18-trixie
    environment:
      POSTGRES_DB: articles
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Postgres1234
    volumes:
      - ./database/init/article/article_baseline.sql:/docker-entrypoint-initdb.d/01_article_baseline.sql:ro
      - ./database/queries/article/seed_reference_data.sql:/docker-entrypoint-initdb.d/02_seed_reference_data.sql:ro

  ## Articles from Australia
  articledb-au:
    image: postgres:18-trixie
    environment:
      POSTGRES_DB: articles
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Postgres1234
    volumes:
      - ./database/init/article/article_baseline.sql:/docker-entrypoint-initdb.d/01_article_baseline.sql:ro
      - ./database/queries/article/seed_reference_data.sql:/docker-entrypoint-initdb.d/02_seed_reference_data.sql:ro

  ## Articles from Asia
  articledb-as:
    image: postgres:18-trixie
    environment:
      POSTGRES_DB: articles
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Postgres1234
    volumes:
      - ./database/init/article/article_baseline.sql:/docker-entrypoint-initdb.d/01_article_baseline.sql:ro
      - ./database/queries/article/seed_reference_data.sql:/docker-entrypoint-initdb.d/02_seed_reference_data.sql:ro

  ## Articles from Antarctica
  articledb-an:
    image: postgres:18-trixie
    environment:
      POSTGRES_DB: articles
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Postgres1234
    volumes:
      - ./database/init/article/article_baseline.sql:/docker-entrypoint-initdb.d/01_article_baseline.sql:ro
      - ./database/queries/article/seed_reference_data.sql:/docker-entrypoint-initdb.d/02_seed_reference_data.sql:ro

  ## Articles from Africa
  articledb-af:
    image: postgres:18-trixie
    environment:
      POSTGRES_DB: articles
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Postgres1234
    volumes:
      - ./database/init/article/article_baseline.sql:/docker-entrypoint-initdb.d/01_article_baseline.sql:ro
      - ./database/queries/article/seed_reference_data.sql:/docker-entrypoint-initdb.d/02_seed_reference_data.sql:ro

  ## Global articles
  articledb-global:
    image: postgres:18-trixie
    environment:
      POSTGRES_DB: articles
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Postgres1234
    volumes:
      - ./database/init/article/article_baseline.sql:/docker-entrypoint-initdb.d/01_article_baseline.sql:ro
      - ./database/queries/article/seed_reference_data.sql:/docker-entrypoint-initdb.d/02_seed_reference_data.sql:ro

  ## Article Service
  articleservice:
    build:
      context: ./apps/article_service/
    image: happyheadlines/article_service
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
    ports:
      - "8080:8080"
#    deploy:
#      replicas: 3
#    depends_on:
#      - articledb-eu
#      - articledb-na
#      - articledb-sa
#      - articledb-au
#      - articledb-as
#      - articledb-an
#      - articledb-af
#      - articledb-global

# ──────────────────────────────────────────────────────────────────────────────
#        Comments 
# ──────────────────────────────────────────────────────────────────────────────

  commentdb:
    image: postgres:18-trixie
    environment:
      POSTGRES_DB: comments
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Postgres1234
    volumes:
      - ./database/init/comment/comment_baseline.sql:/docker-entrypoint-initdb.d/01_comment_baseline.sql:ro
      - ./database/queries/comment/seed_comments.sql:/docker-entrypoint-initdb.d/02_seed_comments.sql:ro

  profanitydb:
    image: postgres:18-trixie
    environment:
      POSTGRES_DB: profanity
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Postgres1234
    volumes:
      - ./database/init/profanity/profanity_baseline.sql:/docker-entrypoint-initdb.d/01_profanity_baseline.sql:ro
      - ./database/queries/profanity/seed_banned_words.sql:/docker-entrypoint-initdb.d/02_seed_banned_words.sql:ro

  profanityservice:
    build:
      context: ./apps/profanity_service/
    image: happyheadlines/profanity_service
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8081
    ports:
      - "8081:8081"

  commentservice:
    build:
      context: ./apps/comment_service/
    image: happyheadlines/comment_service
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8082
    ports:
      - "8082:8082"

# ──────────────────────────────────────────────────────────────────────────────
#        Drafts
# ──────────────────────────────────────────────────────────────────────────────

  draftdb:
    image: postgres:18-trixie
    environment:
      POSTGRES_DB: drafts
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Postgres1234
    volumes:
      - ./database/init/draft/draft_baseline.sql:/docker-entrypoint-initdb.d/01_draft_baseline.sql:ro
      - ./database/queries/draft/seed_drafts.sql:/docker-entrypoint-initdb.d/02_seed_drafts.sql:ro

  draftservice:
    build:
      context: ./apps/draft_service/
    image: happyheadlines/draft_service
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8083
    ports:
      - "8083:8083"

# ──────────────────────────────────────────────────────────────────────────────
#        Clients
# ──────────────────────────────────────────────────────────────────────────────

  happyheadlines:
    build:
      context: ./apps/happy-headlines-web_service/
    image: happyheadlines/happyheadlines_web
    ports:
      - "8000:8000"
