## Structirizr inde i 'C4 diagram*' anvender port 8081
services:
  articledb-eu:
    image: postgres:18-trixie
    environment:
      POSTGRES_DB: articles
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Postgres1234
    volumes:
      - ./database/postgres:/docker-entrypoint-initdb.d:ro

  articledb-na:
    image: postgres:18-trixie
    environment:
      POSTGRES_DB: articles
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Postgres1234
    volumes:
      - ./database/postgres:/docker-entrypoint-initdb.d:ro

  articledb-sa:
    image: postgres:18-trixie
    environment:
      POSTGRES_DB: articles
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Postgres1234
    volumes:
      - ./database/postgres:/docker-entrypoint-initdb.d:ro

  articledb-au:
    image: postgres:18-trixie
    environment:
      POSTGRES_DB: articles
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Postgres1234
    volumes:
      - ./database/postgres:/docker-entrypoint-initdb.d:ro

  articledb-as:
    image: postgres:18-trixie
    environment:
      POSTGRES_DB: articles
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Postgres1234
    volumes:
      - ./database/postgres:/docker-entrypoint-initdb.d:ro

  articledb-an:
    image: postgres:18-trixie
    environment:
      POSTGRES_DB: articles
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Postgres1234
    volumes:
      - ./database/postgres:/docker-entrypoint-initdb.d:ro

  articledb-af:
    image: postgres:18-trixie
    environment:
      POSTGRES_DB: articles
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Postgres1234
    volumes:
      - ./database/postgres:/docker-entrypoint-initdb.d:ro

  articledb-global:
    image: postgres:18-trixie
    environment:
      POSTGRES_DB: articles
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Postgres1234
    volumes:
      - ./database/postgres:/docker-entrypoint-initdb.d:ro

  articleservice:
    build:
      context: ./HappyHeadlines/ArticleService/
    image: happyheadlines/articleservice
    ports:
      - "8080:8080"
    deploy:
      replicas: 3
    depends_on:
      - articledb-eu
      - articledb-na
      - articledb-sa
      - articledb-au
      - articledb-as
      - articledb-an
      - articledb-af
      - articledb-global

  commentdb:
    image: postgres:18-trixie
    environment:
      POSTGRES_DB: comments
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Postgres1234
    volumes:
      - ./database/postgres/comment:/docker-entrypoint-initdb.d:ro

  profanitydb:
    image: postgres:18-trixie
    environment:
      POSTGRES_DB: profanity
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Postgres1234
    volumes:
      - ./database/postgres/profanity:/docker-entrypoint-initdb.d:ro

  profanityservice:
    build:
      context: ./HappyHeadlines/ProfanityService/
    image: happyheadlines/profanityservice
    ports:
      - "8082:8080"
    depends_on:
      - profanitydb

  commentservice:
    build:
      context: ./HappyHeadlines/CommentService/
    image: happyheadlines/commentservice
    ports:
      - "8083:8080"
    depends_on:
      - commentdb
      - profanityservice
