FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build

WORKDIR /src

COPY src/HappyHeadlines.reader.wasm/HappyHeadlines.reader.wasm.csproj HappyHeadlines.reader.wasm/
COPY src/HappyHeadlinesPages.web/HappyHeadlinesPages.web.csproj HappyHeadlinesPages.web/

RUN dotnet restore HappyHeadlines.reader.wasm/HappyHeadlines.reader.wasm.csproj

COPY src/HappyHeadlines.reader.wasm/ HappyHeadlines.reader.wasm/
COPY src/HappyHeadlinesPages.web/ HappyHeadlinesPages.web/

RUN dotnet publish HappyHeadlines.reader.wasm/HappyHeadlines.reader.wasm.csproj \
    -c Release \
    -o /app/publish


FROM nginx:alpine AS final

COPY nginx.reader.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/publish/wwwroot /usr/share/nginx/html

EXPOSE 8001
