-- Journalist ownership moves here from ArticleService: this is where journalists
-- actually work (writing/editing/approving drafts).
CREATE TABLE journalists (
    id         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    operations VARCHAR(255) NOT NULL,
    email      VARCHAR(255),
    phone      VARCHAR(50)
);

-- Generated by running tools/export_journalists_from_article.sh against
-- ArticleService's live database at cutover time (verified: its output matches this
-- block exactly). Re-run that script and regenerate this block if journalists have
-- changed on the ArticleService side since - it is not something `flyway migrate`
-- can do automatically, since ArticleService's journalists table won't exist anymore
-- once its own contract migration (article/V3) has run. Email/phone always come
-- across NULL: ArticleService never collected that data, which is exactly why these
-- columns are nullable rather than required.
INSERT INTO journalists (id, name, operations, email, phone) OVERRIDING SYSTEM VALUE VALUES
    (1, 'Emma Johnson', 'Global News', NULL, NULL),
    (2, 'Liam Chen', 'Tech Today', NULL, NULL),
    (3, 'Sophia Garcia', 'Green Earth', NULL, NULL),
    (4, 'Noah Wilson', 'Health Watch', NULL, NULL),
    (5, 'Olivia Brown', 'Culture Pulse', NULL, NULL),
    (6, 'James Lee', 'Political Insight', NULL, NULL),
    (7, 'Ava Martinez', 'Science Daily', NULL, NULL),
    (8, 'Ethan Davis', 'World Affairs', NULL, NULL);

SELECT setval(pg_get_serial_sequence('journalists', 'id'), (SELECT MAX(id) FROM journalists));

-- Safe to add now, not just later: every existing drafts row's journalist-id columns
-- already resolve to one of the ids just inserted (the id space has only ever come
-- from this same 8-person set copied above), so the constraint can't reject any
-- current data. Purely additive/expand from DraftService's own point of view - it
-- never had a journalist concept before, so there's no old shape to remove here.
ALTER TABLE drafts
    ADD CONSTRAINT fk_drafts_created_by_journalist
        FOREIGN KEY (created_by_journalist_id) REFERENCES journalists(id);

ALTER TABLE drafts
    ADD CONSTRAINT fk_drafts_last_edited_by_journalist
        FOREIGN KEY (last_edited_by_journalist_id) REFERENCES journalists(id);

ALTER TABLE drafts
    ADD CONSTRAINT fk_drafts_approved_by_journalist
        FOREIGN KEY (approved_by_journalist_id) REFERENCES journalists(id);

-- Separate concept from the workflow columns above: who gets credited as an author.
-- "Who did the workflow steps" and "who gets named" are deliberately independent choices.
CREATE TABLE draft_journalists (
    draft_id      UUID NOT NULL REFERENCES drafts(id) ON DELETE CASCADE,
    journalist_id BIGINT NOT NULL REFERENCES journalists(id),
    PRIMARY KEY (draft_id, journalist_id)
);

-- Auto-generated from draft_journalists, but stored as a plain editable string so a
-- journalist can hand-edit it (see DraftService's BylineGenerator).
ALTER TABLE drafts ADD COLUMN byline VARCHAR(255) NOT NULL DEFAULT '';
